### ISSUE TITLE
Wrap-around when scale is timeline

### ISSUE THREAD

**Issue by ejosowitz** [AnalyticsEarth/aePicassoChart#12]
Having an issue that lines and ranges are wrapping around when I have a bottom scale that is a timeline. In the attached screenshot you can see that the blue line and the grey range both are wrapping back to the beginning. The Dimension that is the scale at the bottom is a date/time stamp that runs 24 hours.

![image](https://user-images.githubusercontent.com/21318497/44165665-fa4dc100-a08e-11e8-8de2-21fd52d9fce3.png)

**Comment by AnalyticsEarth** [comment]
I can see this happening also on my test apps. I will look into this and see why its happening.

**Comment by AnalyticsEarth** [comment]
This is due to a new feature added in v0.2.2
If you navigate back to the previous version and download this will work correctly in the meantime while i fix the bug.
https://github.com/AnalyticsEarth/aePicassoChart/tree/d6eba8a384f48c4c4152ecf50bbee1d1ebcedc1e

**Comment by AnalyticsEarth** [comment]
This has been fixed in Version 0.2.3 which can now be downloaded on the master branch.

**Comment by ejosowitz** [comment]
Great, thanks Steve!

On Aug 16, 2018, at 9:05 AM, Steven Pressland <notifications@github.com<mailto:notifications@github.com>> wrote:


This has been fixed in Version 0.2.3 which can now be downloaded on the master branch.
