### ISSUE TITLE
Doesn't work with IE11

### ISSUE THREAD

**Issue by David4BI** [AnalyticsEarth/aePicassoChart#14]
When using IE11 after dragging the extension to the canvas no properties are shown.
When creating a visualization with Chrome and opening the app in IE11 only the tilte is shown.
Looking at the generated html code there are no entries for <svg>.

**Comment by David4BI** [comment]
..there are not entries for svg.

**Comment by AnalyticsEarth** [comment]
HI, this is an issue with IE not supporting modern javascript. At the moment this is not a quick fix. I am working on a version that will be compiled for wider accessibility and performance. When this is done IE11 will be supported.

**Comment by David4BI** [comment]
Thanks for your quick response.
Looking forward for the next version, this extension is awesome!

**Comment by AnalyticsEarth** [comment]
v0.3.0 is now available as a release. note you have to download the release zip rather than the repo now.
Works in IE11 apart from range selection on dimension axis.
let me know if you have any issues.
