### ISSUE TITLE
Installation issues with qExt

### ISSUE THREAD

**Issue by David4BI** [AnalyticsEarth/aePicassoChart#15]
Could you give a short instruction how to install with qExt?
 
I have done the following steps without success:

0. Node.js witn NPM is installed
1. Installed qext with  "npm install -g qext"
2. Downloaded aePicassoChart.zip from https://github.com/AnalyticsEarth/aePicassoChart/releases
3. extraced to C:\aePicassoChart-0.3.0
4. Changed C:\aePicassoChart-0.3.0\aePicassoChart\deployment.config.json to point to Qlik Sense Desktop 
5. Run "npm run watch-webpack-deploy-desktop" while in folder C:\aePicassoChart-0.3.0\aePicassoChart
6. NPM creates error message

> 10 silly lifecycle aePicassoChart@0.3.0~watch-webpack: Args: [ '/d /s /c', 'qext-scripts -w' ]
> 11 silly lifecycle aePicassoChart@0.3.0~watch-webpack: Returned: code: 1  signal: null
> 12 info lifecycle aePicassoChart@0.3.0~watch-webpack: Failed to exec watch-webpack script
> 13 verbose stack Error: aePicassoChart@0.3.0 watch-webpack: `qext-scripts -w`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Development\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Development\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid aePicassoChart@0.3.0
> 15 verbose cwd C:\aePicassoChart-0.3.0\aePicassoChart
> 16 verbose Windows_NT 6.1.7601
> 17 verbose argv "C:\\Development\\nodejs\\node.exe" "C:\\Development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch-webpack"
> 18 verbose node v8.11.2
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error aePicassoChart@0.3.0 watch-webpack: `qext-scripts -w`
> 22 error Exit status 1
> 23 error Failed at the aePicassoChart@0.3.0 watch-webpack script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by AnalyticsEarth** [comment]
you don't need to install with qExt, that is just for development of the extension if you were forking the code. to install download the extension here: https://github.com/AnalyticsEarth/aePicassoChart/releases/download/v0.3.0/aePicassoChart.zip

this is the one you can install using Qlik Sense server or desktop.
