### ISSUE TITLE
v0.30 empty in Qlik Sensse September 2017 Patch 2

### ISSUE THREAD

**Issue by David4BI** [AnalyticsEarth/aePicassoChart#16]
Using the new version under https://github.com/AnalyticsEarth/aePicassoChart/releases/download/v0.3.0/aePicassoChart.zip the chart and property panels are empty (with Qlik Sense September 2017 Patch 2).
Looking at the console there is a error message:

> "No defaults found for: calcCond"

**Comment by AnalyticsEarth** [comment]
this will be due to a new feature that must not be available in the older version you are running, i will build a version without this functionality.

**Comment by AnalyticsEarth** [comment]
hopefully fixed in v0.3.1 now released. Please let me know if you have other issues. I don't have test servers going back that far to check functionality at the moment.
