### ISSUE TITLE
JS error when adding Picasso Designer chart

### ISSUE THREAD

**Issue by ejosowitz** [AnalyticsEarth/aePicassoChart#23]
With the latest build I get a JavaScript error when adding a chart object:

`
load @ qvangular-injector-require-plugin.js:27
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
C @ client.2d62190fe3158c75a942.js:55
callPlugin @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
emit @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
callPlugin @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
j @ client.2d62190fe3158c75a942.js:55
completeLoad @ client.2d62190fe3158c75a942.js:55
onScriptLoad @ client.2d62190fe3158c75a942.js:55
load (async)
req.load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
load @ client.2d62190fe3158c75a942.js:55
fetch @ client.2d62190fe3158c75a942.js:55
check @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
each @ client.2d62190fe3158c75a942.js:55
enable @ client.2d62190fe3158c75a942.js:55
init @ client.2d62190fe3158c75a942.js:55
(anonymous) @ client.2d62190fe3158c75a942.js:55
setTimeout (async)
req.nextTick @ client.2d62190fe3158c75a942.js:55
a @ client.2d62190fe3158c75a942.js:55
requirejs @ client.2d62190fe3158c75a942.js:55
(anonymous) @ 40.8e64cfe8993264ccfc07.js:576
n @ 40.8e64cfe8993264ccfc07.js:576
p @ client.2d62190fe3158c75a942.js:42
i @ client.2d62190fe3158c75a942.js:42
e.(anonymous function) @ client.2d62190fe3158c75a942.js:42
p @ client.2d62190fe3158c75a942.js:42
t @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
Promise.then (async)
t @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
i @ client.2d62190fe3158c75a942.js:42
i @ client.2d62190fe3158c75a942.js:42
e.(anonymous function) @ client.2d62190fe3158c75a942.js:42
l.async @ client.2d62190fe3158c75a942.js:42
l @ 40.8e64cfe8993264ccfc07.js:576
c @ 40.8e64cfe8993264ccfc07.js:576
c @ 40.8e64cfe8993264ccfc07.js:527
u @ 40.8e64cfe8993264ccfc07.js:527
(anonymous) @ 40.8e64cfe8993264ccfc07.js:527
u @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
$eval @ client.2d62190fe3158c75a942.js:42
$digest @ client.2d62190fe3158c75a942.js:42
$apply @ client.2d62190fe3158c75a942.js:42
$ @ client.2d62190fe3158c75a942.js:42
C @ client.2d62190fe3158c75a942.js:42
e @ client.2d62190fe3158c75a942.js:42
load (async)
(anonymous) @ client.2d62190fe3158c75a942.js:42
$ @ client.2d62190fe3158c75a942.js:42
m @ client.2d62190fe3158c75a942.js:42
u @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
$eval @ client.2d62190fe3158c75a942.js:42
$digest @ client.2d62190fe3158c75a942.js:42
$apply @ client.2d62190fe3158c75a942.js:42
(anonymous) @ qvangular.5be57daa16f972d532e2.js:20
(anonymous) @ 40.8e64cfe8993264ccfc07.js:493
setTimeout (async)
d.debounceApply @ 40.8e64cfe8993264ccfc07.js:493
t @ 40.8e64cfe8993264ccfc07.js:493
(anonymous) @ 40.8e64cfe8993264ccfc07.js:493
u @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
$eval @ client.2d62190fe3158c75a942.js:42
$digest @ client.2d62190fe3158c75a942.js:42
$apply @ client.2d62190fe3158c75a942.js:42
(anonymous) @ qvangular.5be57daa16f972d532e2.js:20
(anonymous) @ 40.8e64cfe8993264ccfc07.js:493
setTimeout (async)
d.debounceApply @ 40.8e64cfe8993264ccfc07.js:493
t @ 40.8e64cfe8993264ccfc07.js:493
(anonymous) @ 40.8e64cfe8993264ccfc07.js:493
u @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
$eval @ client.2d62190fe3158c75a942.js:42
$digest @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
d @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
setTimeout (async)
An.i.defer @ client.2d62190fe3158c75a942.js:42
$evalAsync @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
s @ client.2d62190fe3158c75a942.js:42
then @ client.2d62190fe3158c75a942.js:42
v @ client.2d62190fe3158c75a942.js:42
u @ 40.8e64cfe8993264ccfc07.js:24
u @ 40.8e64cfe8993264ccfc07.js:493
d @ 40.8e64cfe8993264ccfc07.js:493
(anonymous) @ 40.8e64cfe8993264ccfc07.js:493
c @ client.2d62190fe3158c75a942.js:31
l @ client.2d62190fe3158c75a942.js:31
setTimeout (async)
(anonymous) @ client.2d62190fe3158c75a942.js:31
s @ client.2d62190fe3158c75a942.js:31
add @ client.2d62190fe3158c75a942.js:31
(anonymous) @ client.2d62190fe3158c75a942.js:31
Deferred @ client.2d62190fe3158c75a942.js:31
then @ client.2d62190fe3158c75a942.js:31
(anonymous) @ 40.8e64cfe8993264ccfc07.js:493
u @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
$eval @ client.2d62190fe3158c75a942.js:42
$digest @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
d @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
setTimeout (async)
An.i.defer @ client.2d62190fe3158c75a942.js:42
$evalAsync @ client.2d62190fe3158c75a942.js:42
(anonymous) @ client.2d62190fe3158c75a942.js:42
s @ client.2d62190fe3158c75a942.js:42
then @ client.2d62190fe3158c75a942.js:42
p @ 40.8e64cfe8993264ccfc07.js:493
(anonymous) @ 40.8e64cfe8993264ccfc07.js:493
t.emit @ 4.77484b46c158fedf3b9f.js:7
e @ 4.77484b46c158fedf3b9f.js:7
10:58:55.545 aePicassoChart.js:1 Uncaught SyntaxError: Unexpected identifier
10:58:55.548 40.8e64cfe8993264ccfc07.js:576 Uncaught TypeError: Cannot read property '__esModule' of undefined
    at 40.8e64cfe8993264ccfc07.js:576
    at Object.execCb (client.2d62190fe3158c75a942.js:55)
    at n.check (client.2d62190fe3158c75a942.js:55)
    at n.<anonymous> (client.2d62190fe3158c75a942.js:55)
    at client.2d62190fe3158c75a942.js:55
    at client.2d62190fe3158c75a942.js:55
    at each (client.2d62190fe3158c75a942.js:55)
    at n.emit (client.2d62190fe3158c75a942.js:55)
    at n.check (client.2d62190fe3158c75a942.js:55)
    at n.enable (client.2d62190fe3158c75a942.js:55)`

**Comment by AnalyticsEarth** [comment]
Sometimes this can occur due to Qlik Sense client caching old versions of files. Can you try reloading without the cache and see if this continues. If it does, please let me know the version of sense you are using.

**Comment by ejosowitz** [comment]
I've cleared the client cache and no change. Do you perhaps mean clearing a cache server-side?

**Comment by AnalyticsEarth** [comment]
can you confirm which version of sense you are running and which browser. I am not aware of this error in any of my testing.

**Comment by ejosowitz** [comment]
QS June 2018, using Google Chrome 68.0.3340 Mac OS X

**Comment by AnalyticsEarth** [comment]
can you confirm that you have downloaded the release zip and not the git-hub repository. The extension requires the code to be compiled before loading into qlik sense.

https://github.com/AnalyticsEarth/aePicassoChart/releases/download/v0.4.0/aePicassoChart.zip
