### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by ejosowitz** [AnalyticsEarth/aePicassoChart#3]
Would be very helpful to show data values in mouseover on the visualization!

**Comment by AnalyticsEarth** [comment]
I will add this to the list, at the moment I am focusing on support for standard components. Tooltips would require a custom component. As the extension evolves then this will definitely be on this list of features to add.

**Comment by ejosowitz** [comment]
Nice! Is this a solo project or are others at Qlik involved and helping?

Erik Josowitz, SVP Technology and Strategy
AWL, Inc.
________________________________

**Comment by AnalyticsEarth** [comment]
The tooltip component had been developed on the picasso.js project. once this is in the build release I will look to add this to the extension.

**Comment by AnalyticsEarth** [comment]
Added in version 0.4.0 (for existing charts you have to toggle it on using the property in add-on)
