### ISSUE TITLE
Picasso cannot be opened in Qlik Dev-Hub

### ISSUE THREAD

**Issue by LenaRubeni** [AnalyticsEarth/aePicassoChart#34]
Hi, 

I am able to import Picasso into Qlik. But when I want to include additional Code for Special Chart types, my dev-hub does not open the Extension because a wbl.file is missing. 
Does anyone has the same Problem?
Looking Forward Hearing from you!
Greetings, 
Lena

**Comment by AnalyticsEarth** [comment]
This extension is too complex to be developed using the Dev-Hub. You will require a IDE and configuration building node.js/NPM managed applications.
