### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by pgrizz28** [AnalyticsEarth/aePicassoChart#7]
Hi,

This looks great, but...

Installed through extensions in QMC on 4 node cluster, version June2018, and when editing a sheet, dragging the extension to the worksheet, it doesn't. It then prevents any objects being added.

Is there compatibility issues with this version or am I missing something?

Thanks.

**Comment by AnalyticsEarth** [comment]
i've not seen that before. Are there any errors in the console? can you also try and do a hard refresh of the page to check you have the latest assets loading?

works fine on all my June 2018 servers.

**Comment by pgrizz28** [comment]
Hi

No errors show. Just doesn't recognise object been added to the sheet. Also
prevents further objects to be added after trying.

Given hard reload, and have same experience on chrome and ie.

Thanks

**Comment by AnalyticsEarth** [comment]
please try the new version by downloading the release and let me know if you still have issues.
the code has been completely overhauled, so may solve any issues you had.

**Comment by AnalyticsEarth** [comment]
Closed as no further contact
